# Generated by Django 5.2.5 on 2025-08-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lessonrequest',
            index=models.Index(fields=['status', 'created_at'], name='core_lesson_status_ad8b3c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonrequest',
            index=models.Index(fields=['start_time'], name='core_lesson_start_t_1253dd_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['rating'], name='core_tutorp_rating_5a6226_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorprofile',
            index=models.Index(fields=['hourly_rate'], name='core_tutorp_hourly__44ea01_idx'),
        ),
    ]
