name: Backend CI

on:
  push:
    paths-ignore:
      - "README.md"
      - ".github/**"
  pull_request:

jobs:
  test:
    name: Run Django tests
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: core.settings  # settings.py yolu doğru olmalı
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Check Django setup
        run: |
          python --version
          python -c "import django; print('Django:', django.get_version())"

      - name: Run tests
        run: |
          python manage.py test -v 2
