name: Backend CI

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  test:
    name: Run Django tests
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: core.settings   # settings yolun farklıysa değiştir
      PYTHONUNBUFFERED: "1"
      SECRET_KEY: "ci-secret-key"
      DEBUG: "0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt bulunamadı, temel bağımlılıklar kuruluyor..."
            pip install "Django>=5,<6" djangorestframework django-filter \
                        drf-spectacular djangorestframework-simplejwt django-cors-headers

      - name: Django check & migrate (SQLite)
        run: |
          python --version
          python -c "import django; print('Django:', django.get_version())"
          if [ -f manage.py ]; then
            python manage.py check
            python manage.py migrate --noinput
          else
            echo "manage.py bulunamadı"; exit 1
          fi

      - name: Run tests
        run: |
          python manage.py test -v 2
